project_id = "mpnizkjntkutpxevqzxx"

[functions.check-subscriptions]
verify_jwt = false

[functions.send-expiry-alerts]
verify_jwt = false

[functions.manage-commercial-user]
verify_jwt = false

[functions.scrape-businesses]
verify_jwt = false

[functions.extract-businesses-from-text]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.email-webhook]
verify_jwt = false

[functions.process-cadences]
verify_jwt = false

[functions.receive-email]
verify_jwt = false

[functions.notify-business]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
