// Auto-generated by lovable-exec - DO NOT EDIT
import { defineConfig } from "vite";
import baseConfig from "../vite.config.ts";
import { componentTagger } from "lovable-tagger";
import { VitePWA } from "vite-plugin-pwa";

const userConfig = baseConfig;
const lovableTagger = componentTagger();

export default defineConfig(async (configEnv) => {
  const resolvedConfig =
    typeof userConfig === "function" ? await userConfig(configEnv) : userConfig;

  const rawPlugins = resolvedConfig?.plugins;
  const plugins = Array.isArray(rawPlugins) ? rawPlugins : rawPlugins ? [rawPlugins] : [];

  // Remove existing PWA and lovable-tagger plugins
  const existingPlugins = plugins.filter(
    (p) => p?.name !== "lovable-tagger" && p?.name !== "vite-plugin-pwa"
  );

  return {
    ...resolvedConfig,
    build: {
      ...resolvedConfig?.build,
      chunkSizeWarningLimit: 1000,
      rollupOptions: {
        ...resolvedConfig?.build?.rollupOptions,
        output: {
          ...resolvedConfig?.build?.rollupOptions?.output,
          manualChunks(id: string) {
            if (id.includes("node_modules")) {
              if (
                id.includes("react") ||
                id.includes("react-dom") ||
                id.includes("react-router")
              ) {
                return "vendor-react";
              }
              if (id.includes("@supabase")) {
                return "vendor-supabase";
              }
              if (id.includes("jspdf") || id.includes("html2canvas")) {
                return "vendor-pdf";
              }
              if (id.includes("recharts") || id.includes("d3-")) {
                return "vendor-charts";
              }
              if (id.includes("@radix-ui") || id.includes("lucide-react")) {
                return "vendor-ui";
              }
              return "vendor-misc";
            }
          },
        },
      },
    },
    plugins: [
      ...existingPlugins,
      lovableTagger,
      VitePWA({
        registerType: "autoUpdate",
        includeAssets: ["favicon.ico", "robots.txt"],
        manifest: {
          name: "Pede Direto - Contactos que resolvem",
          short_name: "Pede Direto",
          description:
            "Encontre rapidamente o contacto que resolve o seu problema. Restaurantes, serviços, lojas e profissionais.",
          theme_color: "#16a34a",
          background_color: "#ffffff",
          display: "standalone",
          orientation: "portrait-primary",
          start_url: "/",
          scope: "/",
          categories: ["business", "utilities", "lifestyle"],
          icons: [
            {
              src: "/favicon.ico",
              sizes: "64x64",
              type: "image/x-icon",
            },
            {
              src: "/pwa-192x192.png",
              sizes: "192x192",
              type: "image/png",
            },
            {
              src: "/pwa-512x512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "any maskable",
            },
          ],
        },
        workbox: {
          navigateFallbackDenylist: [/^\/~oauth/],
          maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
          globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
          runtimeCaching: [
            {
              urlPattern: /\/rest\/v1\/categories/,
              handler: "StaleWhileRevalidate",
              options: {
                cacheName: "categories-cache",
                expiration: {
                  maxEntries: 50,
                  maxAgeSeconds: 60 * 60 * 24,
                },
              },
            },
            {
              urlPattern: /\/rest\/v1\/subcategories/,
              handler: "StaleWhileRevalidate",
              options: {
                cacheName: "subcategories-cache",
                expiration: {
                  maxEntries: 200,
                  maxAgeSeconds: 60 * 60 * 24,
                },
              },
            },
            {
              urlPattern: /\/rest\/v1\/businesses/,
              handler: "StaleWhileRevalidate",
              options: {
                cacheName: "businesses-cache",
                expiration: {
                  maxEntries: 1000,
                  maxAgeSeconds: 60 * 60 * 12,
                },
              },
            },
            {
              urlPattern: /\/rest\/v1\/business_subcategories/,
              handler: "StaleWhileRevalidate",
              options: {
                cacheName: "business-subcategories-cache",
                expiration: {
                  maxEntries: 500,
                  maxAgeSeconds: 60 * 60 * 12,
                },
              },
            },
            {
              urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
              handler: "CacheFirst",
              options: {
                cacheName: "images-cache",
                expiration: {
                  maxEntries: 100,
                  maxAgeSeconds: 60 * 60 * 24 * 7,
                },
              },
            },
          ],
        },
      }),
    ],
  };
});
